version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud
      MYSQL_USER: user  
      MYSQL_PASSWORD: 12A34B56C
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"