services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: //mysq_passwordd
      MYSQL_DATABASE:  //database name 
      MYSQL_USER: //useDb
      MYSQL_PASSWORD: //passwordDb
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"
